name: XTATUZ_POC_BACKEND_DEVELOPMENT

on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: [self-hosted, xtatuz-poc-dev]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Create environment file
        run: |
          echo $'NODE_ENV=${{secrets.NODE_ENV}}\n' >> .env
          echo $'PORT=${{secrets.PORT}}\n' >> .env
          echo $'POSTGRES_HOST=${{secrets.POSTGRES_HOST}}\n' >> .env
          echo $'POSTGRES_PORT=${{secrets.POSTGRES_PORT}}\n' >> .env
          echo $'POSTGRES_USER=${{secrets.POSTGRES_USER}}\n' >> .env
          echo $'POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}\n' >> .env
          echo $'POSTGRES_DATABASE=${{secrets.POSTGRES_DATABASE}}\n' >> .env
          echo $'SYNCHRONIZE=${{secrets.SYNCHRONIZE}}\n' >> .env
          echo $'JWT_SECRET=${{secrets.JWT_SECRET}}\n' >> .env
          echo $'JWT_REFRESH=${{secrets.JWT_REFRESH}}\n' >> .env
          echo $'SECRET_EXPIRES_IN=${{secrets.SECRET_EXPIRES_IN}}\n' >> .env
          echo $'REFRESH_EXPIRES_IN=${{secrets.REFRESH_EXPIRES_IN}}\n' >> .env
          echo $'RPC_PROVIDER=${{secrets.RPC_PROVIDER}}\n' >> .env
          echo $'PRIVATE_KEY=${{secrets.PRIVATE_KEY}}\n' >> .env
          echo $'CONTRACT_XTATUZ_ADDRESS=${{secrets.CONTRACT_XTATUZ_ADDRESS}}\n' >> .env
          echo $'AWS_S3_BUCKET_NAME=${{secrets.AWS_S3_BUCKET_NAME}}\n' >> .env
          echo $'AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}\n' >> .env
          echo $'AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}\n' >> .env
          echo $'AWS_REGION=${{secrets.AWS_REGION}}\n' >> .env
      - name: Run docker compose
        run: |
          docker-compose up -d --build
      - name: Clear unused containers
        run: |
          docker system prune -f
